[application]
name = "ani-tracker"

[bundle]
identifier = "top.likanug.ani-tracker"
publisher = "likanug"

[web.app]

# HTML title tag content
title = "ani-tracker"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
